BEGIN;
CREATE SEQUENCE IF NOT EXISTS crypto_sequence START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS user_sequence START WITH 1 INCREMENT BY 1;

CREATE TABLE app_user
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name VARCHAR(255),
    crypto_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_app_user PRIMARY KEY (id)
);

CREATE TABLE crypto
(
    id     BIGINT NOT NULL,
    symbol VARCHAR(255),
    price  INTEGER,
    CONSTRAINT pk_crypto PRIMARY KEY (id)
);

INSERT INTO crypto (id, symbol)
VALUES (90, 'BTC');

INSERT INTO crypto (id, symbol)
VALUES (80, 'ETH');

INSERT INTO crypto (id, symbol)
VALUES (48543, 'SOL');

ALTER TABLE app_user
    ADD CONSTRAINT FK_USER_ON_CRYPTO FOREIGN KEY (crypto_id) REFERENCES crypto (id);;
COMMIT;